### ISSUE TITLE
library broken by SDK 1.0.0

### ISSUE THREAD

**Issue by rothskeller** [theopolisme/react-native-stripe-terminal#3]
After working around issue #2, I encountered subsequent build errors about APIs that were "no longer available".  It appears that your library is based on Stripe Terminal SDK 1.0.0b6, and these deprecations were added in 1.0.0rc1.  I'm currently trying to build with 1.0.0 final, which was released a few days ago.

The specific errors:

```
info /Users/stever/src/orders/AtTheDoor/node_modules/react-native-stripe-terminal/ios/RNStripeTerminal.m:52:46: error: 'SCPDeviceTypeReaderSimulator' is unavailable: Choosing a simulated reader has moved to SCPDiscoveryConfiguration.init
info              @"DeviceTypeReaderSimulator": @(SCPDeviceTypeReaderSimulator),
                                             ^
info In file included from /Users/stever/src/orders/AtTheDoor/node_modules/react-native-stripe-terminal/ios/RNStripeTerminal.m:1:
In file included from /Users/stever/src/orders/AtTheDoor/node_modules/react-native-stripe-terminal/ios/RNStripeTerminal.h:12:
In file included from /Users/stever/src/orders/AtTheDoor/ios/Pods/StripeTerminal/Carthage/Build/iOS/StripeTerminal.framework/Headers/StripeTerminal.h:21:
/Users/stever/src/orders/AtTheDoor/ios/Pods/StripeTerminal/Carthage/Build/iOS/StripeTerminal.framework/Headers/SCPDeprecations.h:204:28: note: 'SCPDeviceTypeReaderSimulator' has been explicitly marked unavailable here

extern const SCPDeviceType SCPDeviceTypeReaderSimulator

info
info                            ^
info /Users/stever/src/orders/AtTheDoor/node_modules/react-native-stripe-terminal/ios/RNStripeTerminal.m:57
```

and:

```
info /Users/stever/src/orders/AtTheDoor/node_modules/react-native-stripe-terminal/ios/RNStripeTerminal.m:138:76: error: 'initWithDeviceType:method:' is unavailable: Use `initWithDeviceType:discoveryMethod:simulated:` instead
    SCPDiscoveryConfiguration *config = [[SCPDiscoveryConfiguration alloc] initWithDeviceType:(SCPDeviceType)deviceType method:(SCPDiscoveryMethod)method];
                                                                           ^
In file included from /Users/stever/src/orders/AtTheDoor/node_modules/react-native-stripe-terminal/ios/RNStripeTerminal.m:1:
In file included from /Users/stever/src/orders/AtTheDoor/node_modules/react-native-stripe-terminal/ios/RNStripeTerminal.h:12:
In file included from /Users/stever/src/orders/AtTheDoor/ios/Pods/StripeTerminal/Carthage/Build/iOS/StripeTerminal.framework/Headers/StripeTerminal.h:21:
/Users/stever/src/orders/AtTheDoor/ios/Pods/StripeTerminal/Carthage/Build/iOS/StripeTerminal.framework/Headers/SCPDeprecations.h:212:1: note: 'initWithDeviceType:method:' has been explicitly marked unavailable here
- (nullable instancetype)initWithDeviceType:(SCPDeviceType)deviceType method:(SCPDiscoveryMethod)method
^

info /Users/stever/src/orders/AtTheDoor/node_modules/react-native-stripe-terminal/ios/RNStripeTerminal.m
```

**Comment by theopolisme** [comment]
Hi, yes, thanks for making this a formal issue - right now the library is indeed based on b6 and has yet to be updated to the stable release. It would be great if you could make a pull request to accommodate the changes necessary for the rc/final version! Since we already abstract the React side of things away into `createPayment`, it could actually potentially be very easy to upgrade.

I unfortunately have been quite busy lately so haven't had much free time to devote to this project. At work we are planning to integrate Stripe Terminal into a second React Native app, so when/if that happens I would likely be able to put in the time to upgrade this library to rc/final as well, but that may not be for a few weks.

Happy to provide any guidance / pointers that I can if you want to dive in, though!

Thanks again,
Theo
